### ISSUE TITLE
UX Work: User Story for "Get Involved" design update

### ISSUE THREAD

**Issue by UXBrendan** [orcasound/product#109]
@Shienny1- thanks so much for your work on updating the design of the Get Involved page [Orcahome Redesign: Get Involved Page UX Update](https://github.com/orcasound/product/issues/30)! 

Your next task is to write a user story outlining your design update of the "Get Involved" page to assign to devs for production. You can find User Story resources here: [User Story Training](https://github.com/orcasound/product/wiki/2.-UX-Resources#user-story-training)

**Comment by UXBrendan** [comment]
@Shienny1 

Let me know if you have any questions. Looking forward to the user story that will be assigned to devs.

**Comment by Shienny1** [comment]
**User Story _ Getting Involved Page**


**User Story**
AS a New Orcahome user I WANT to be able to easily navigate through the page and find relevant links  SO THAT I can complete my goal without having to read the all the text on the page. 


**Description**
The intent of this story is to inform the Developer team on the final design changes made on the Get Involved page.


**Notes:**

- All hyperlinks are removed from text. Buttons are added instead.
- Cards are introduced to clearly separate Orcanode and Orcasite information.
- Icons for Github, Slack, Trello, Play Orcasound,  mail, are introduced on this page 
- All buttons and icons are linked to the correct destination per existing orcahome.net website.




**Acceptance Criteria**
GIVEN I open the Orcasound Get_Involved page WHEN I scroll through the page THEN I see buttons that are uniform and clearly indicate the destination of each button or icons.

Figma file: https://www.figma.com/file/AKxnlPthLEMQyYrYuMWqOW/Orcahome-Dev-Design?type=design&node-id=204%3A546&mode=design&t=y3h0QX1UXlWuh9fb-1

Protoype: 
https://www.figma.com/proto/AKxnlPthLEMQyYrYuMWqOW/Orcahome-Dev-Design?page-id=0%3A1&node-id=204-546&starting-point-node-id=204%3A546&mode=design&t=8aNW3RZWHwoFs0MH-1

**Comment by Shienny1** [comment]
@UXBrendan
Hi Brendan, Sorry it took so long for me to complete this. I hope this is sufficient!  Let me know if you need me to revise anything. 
Thank you,
Shienny

**Comment by UXBrendan** [comment]
@Shienny1 

No worries! Thanks for writing the user story. I've finally got around to sending it to the devs.
