### ISSUE TITLE
UX Work: User Story for Release 1 Navigation Bars

### ISSUE THREAD

**Issue by UXBrendan** [orcasound/product#111]
Please write a user story outlining your design update of the "Get Involved" page to assign to devs for production. You can find User Story resources here: [User Story Training](https://github.com/orcasound/product/wiki/2.-UX-Resources#user-story-training)

Figma file page (Navigation Bars page): https://www.figma.com/file/AKxnlPthLEMQyYrYuMWqOW/Orcahome-Dev-Design?type=design&node-id=517-94&mode=design

**Comment by UXBrendan** [comment]
@verabao 

Let me know if you have any questions. Looking forward to the user story that will be assigned to devs.

**Comment by Shivangi-2789** [comment]
**User Story**
AS a New Orcahome user I WANT to be able to easily navigate through the page and find relevant links SO THAT I can complete my goal without having to read the all the text on the page.

**Description**
The intent of this story is to implement the UI finalized design from the Orcasound UX/UI team for the website redesign on the Navigation Bars.

**Notes**
Use this Figma file page (Navigation Bars page): https://www.figma.com/file/AKxnlPthLEMQyYrYuMWqOW/Orcahome-Dev-Design?type=design&node-id=517-94&mode=design

**Acceptance Criteria**
GIVEN I open the Orcasound website WHEN I look at the pages THEN I see a UI that matches the attached UX/UI design.
